### ISSUE TITLE
perfect

### ISSUE THREAD

**Issue by lockonD** [Tryking/AudioRecord#2]
Can you perfect the AudioManager class, and some methods have not been found?
  mAudioManager.discardRecording();
  mAudioManager.stopRecoding();
  mAudioManager.discardRecording();
  R.drawable.common_btn_yellow_dash_frame
  R.drawable.common_btn_yellow_solid
  R.drawable.common_btn_yellow_solid
Thank you.

**Comment by Tryking** [comment]
I'm so sorry. I haven't had the code and I don't want to read it. But I remember my code was correct.

**Comment by Itachi110** [comment]
hehe

**Comment by Itachi6688** [comment]
@Tryking hehe

**Comment by HOLDfoot** [comment]
@Tryking hehe!! Can I report the responsitory

**Comment by Tryking** [comment]
> @Tryking hehe!! Can I report the responsitory

Sure, just do it.
